apiVersion: v1
kind: Secret
metadata:
  name: collector-secrets
  namespace: collector-shop
type: Opaque
stringData:
  JWT_SECRET: "poc-super-secret-key-for-local-dev"
  DATABASE_URL: "postgresql://root:rootpassword@postgres-service:5432/collector_db"
  STRIPE_SECRET_KEY: "sk_test_REPLACE_WITH_YOUR_STRIPE_KEY"
  STRIPE_WEBHOOK_SECRET: "whsec_mock"
  POSTGRES_USER: "root"
  POSTGRES_PASSWORD: "rootpassword"
  POSTGRES_DB: "collector_db"
